defaults: &defaults
  adapter: mysql2
  username: root
  password: root
  host: 127.0.0.1

development:
  database: board_development
  <<: *defaults

test: &test
  database: board_test
  <<: *defaults

cucumber:
  <<: *test
